### PR TITLE
[Core]Change the access level of MultiMsgEntity's constructor to public

### PR DESCRIPTION
**Pull request by sweetymajo**
To ensure consistency with other IMessageEntity classes, programs developed with Core can directly use the constructor to initialize MultiMsgEntity objects.

### CODE REVIEW

**Comment by CwkDark** [comment]
The [`MessageBuilder.MultiMsg`](https://github.com/LagrangeDev/Lagrange.Core/blob/7f67ae9377b4075ddb75505257fc55f85dbad54c/Lagrange.Core/Message/MessageBuilder.cs#L76) method should be used.

**Comment by sweetymajo** [comment]
> The [`MessageBuilder.MultiMsg`](https://github.com/LagrangeDev/Lagrange.Core/blob/7f67ae9377b4075ddb75505257fc55f85dbad54c/Lagrange.Core/Message/MessageBuilder.cs#L76) method should be used.

I know the MessageBuilder.MultiMsg method, but this method processes parameters by converting arrays to lists. However, many APIs currently return MessageChain collections as lists rather than arrays. So, calling this method essentially involves converting a list to an array and then back to a list. Isn't this approach somewhat unreasonable? Therefore, after noticing that other classes based on the IMessageEntity interface all have public constructors, I believe that MultiMsgEntity should also have a public constructor.

**Review by CwkDark — APPROVED** [review]

**Comment by CwkDark** [comment]
Yes, there is a problem with the implementation here, actually the array is used here to use `parameters`.

Maybe we need to add `public MessageBuilder MultiMsg(uint? groupUin = null, List<MessageChain> chains)` and `public MessageBuilder MultiMsg(uint? groupUin = null, List<MessageBuilder> chains)` methods to handle this?

But this is another issue.

Regarding the permissions of the constructor method, after asking the owner, it is possible that the permissions of the `MultiMsgEntity` constructor method are set to `internal` by mistake.

Thanks for your contribution!

**Comment by CwkDark** [comment]
Oh ...... Your commit isn't signed. You need to sign it before we can merge it.

**Comment by sweetymajo** [comment]
> Oh ...... Your commit isn't signed. You need to sign it before we can merge it.
> 
> You can learn how to sign a commit by checking out [this documentation](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification)

Thank you for the reminder. I have already sign the commit.

**Pull request merged**
